<a href="https://colab.research.google.com/github/TANMAY123484/numpy/blob/main/Neural%20network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
x=np.array(([3,5],[5,1],[10,2]),dtype=float)
y=np.array(([75],[82],[93]),dtype=float)

In [ ]:
print(x)
print(y)

[[ 3.  5.]
 [ 5.  1.]
 [10.  2.]]
[[75.]
 [82.]
 [93.]]


In [ ]:
x

array([[ 3.,  5.],
       [ 5.,  1.],
       [10.,  2.]])

In [ ]:
y

array([[75.],
       [82.],
       [93.]])

In [ ]:
x_norm=x/np.amax(x,axis=0)
y_norm=y/100 #Max test score is 100

In [ ]:
x_norm

array([[0.3, 1. ],
       [0.5, 0.2],
       [1. , 0.4]])

In [ ]:
y_norm

array([[0.75],
       [0.82],
       [0.93]])

In [37]:
# Neural network
class Neural_Network(object):
  def __init__(self):
    # Define Hyperparameters
    self.inputLayerSize=2
    self.hiddenLayerSize=3
    self.outputLayerSize=1
    self. W1 = np.random.randn(self.inputLayerSize,self.hiddenLayerSize)
    self. W2 = np.random.randn(self.hiddenLayerSize,self.outputLayerSize)
  def forward(self,X):
    self.z2=np.dot(X,self.W1)
    self.a2=np.sigmoid(self.z2)
    self.z3=np.dot(self.a2,self.W2)
    y_hat=self.sigmoid(self.z3)
    return y_hat
    

In [41]:
def sigmoid(self,z):
  return 1/(1+np.exp(-z))

In [42]:
NN=Neural_Network()
y_hat=NN.forward(x)
y_hat

AttributeError: ignored

In [39]:
def sigmoid(self,z):
  return 1/(1+np.exp(-z))

In [ ]:
def forward(self,x):
  #Propogate inputs through network
  

In [ ]:
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [ ]:
sigmoid(1)

0.7310585786300049

In [ ]:
sigmoid(np.array([-1,0,1]))

array([0.26894142, 0.5       , 0.73105858])

In [ ]:
sigmoid(np.random.randn(3,3))

array([[0.12211812, 0.52280212, 0.42102643],
       [0.21022008, 0.5402568 , 0.12819568],
       [0.58947248, 0.45206808, 0.52195503]])